{"name": "test_div_zero_param[0-10-None]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.0 == None\n +  where 0.0 = div(0, 10)", "trace": "num1 = 0, num2 = 10, exception = None\n\n    @pytest.mark.exception\n    @pytest.mark.parametrize(\"num1, num2,exception\", {\n        (0, 10, None),\n        (10, 0, None),\n        (0, 0, None)\n    })\n    def test_div_zero_param(num1, num2,exception):\n>       assert div(num1, num2) == exception\nE       assert 0.0 == None\nE        +  where 0.0 = div(0, 10)\n\nunit\\test_div.py:60: AssertionError"}, "parameters": [{"name": "num1", "value": "0"}, {"name": "num2", "value": "10"}, {"name": "exception", "value": "None"}], "start": 1577236597459, "stop": 1577236597460, "uuid": "5ef41cf0-1869-4b0c-ae14-c1fa032a4309", "historyId": "32f7954b0740efd71821716606003427", "testCaseId": "488092d0a8d10c164aeec01e190a2c7d", "fullName": "test_div#test_div_zero_param", "labels": [{"name": "tag", "value": "exception"}, {"name": "suite", "value": "test_div"}, {"name": "host", "value": "MS-20170607LVPH"}, {"name": "thread", "value": "5016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_div"}]}