{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\nunit\\test_pytest.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "aa4747f3-ce68-4ac9-b54d-32bb9857b125-attachment.txt", "type": "text/plain"}], "start": 1577236597503, "stop": 1577236597504, "uuid": "9229e44c-ab88-4337-9d3d-afc294f34afa", "historyId": "df9bcdcaf6673f9b34f46d024ee19955", "testCaseId": "d936ef931c01e1a27d2f3ee0f0d86c3d", "fullName": "test_pytest#test_answer", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "MS-20170607LVPH"}, {"name": "thread", "value": "5016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}